### ISSUE TITLE
Ignore groovy-stubs directory

### ISSUE THREAD

**Issue by asturio** [mycila/gmavenplus-intellij-plugin#1]
Hi,

I use the gmaven-plus plugin in my project, and I use IntelliJ and maven. When maven generate the groovy-stubs, it generates in target/generated-sources/groovy-stubs. So IntelliJ find sources of the same class in 2 directories. The first one in the real groovy source, and the second one the generated groovy-(java)-stub.

It would be very nice, if your plugin could detect this and set in IntelliJ, that the groovy-stubs directory should also be ignored. Like setting the directory as "Excluded" in the Project Settings->Modules->Sources tab

**Comment by TeknoMatik** [comment]
Hi, 

Can confirm, was struggling last few days when finally figure out that it was gmavenplus plugin problem. 
Can you please exclude those two folders?
