### ISSUE TITLE
Document that this is now built-in to IntelliJ

### ISSUE THREAD

**Issue by keeganwitt** [mycila/gmavenplus-intellij-plugin#3]
I'm not totally sure when the fix for [IDEA-119931](https://youtrack.jetbrains.com/issue/IDEA-119931) landed.  The issue says this is fixed starting in 192.4342, 191.7705.  But when I look in the Git log, I find c46040ccba5285543f41ab2ae50ad6a979d9f910 starting with 192.4488.21.

But either way, this plugin should no longer be necessary.  We should document that if users are on a recent IntelliJ, they don't need to install this.
Additionally, it may be worth editing the plugin descriptor so that it will stay disabled on newer IntelliJ versions.

**Comment by mathieucarbou** [comment]
I have asked for it to be removed.

**Comment by keeganwitt** [comment]
It could potentially still be useful for users that are on an old version under a perpetual fallback license I suppose.

**Comment by leonard84** [comment]
As this is now explicitly marked as incompatible with the latest version, and thus causing an error message, maybe you could add a disclaimer in the plugin description. 
https://plugins.jetbrains.com/plugin/7442-gmavenplus-intellij-plugin

**Comment by mathieucarbou** [comment]
the plugin is marked deprecated already.
